version: "3.8"

services:
  app:
    container_name: go-start
    image: go-start
    build:
      context: .
      dockerfile: ./docker/app.dockerfile
    volumes:
      - .:/app
    env_file: .env
    ports:
      - 3000:3000